/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

/// <reference types="truffle-typings" />

import * as TruffleContracts from ".";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(
        name: "BitPackingERC20"
      ): TruffleContracts.BitPackingERC20Contract;
      require(name: "BitPackingHodl"): TruffleContracts.BitPackingHodlContract;
      require(name: "Boostable"): TruffleContracts.BoostableContract;
      require(name: "BoostableERC20"): TruffleContracts.BoostableERC20Contract;
      require(name: "BoostableHodl"): TruffleContracts.BoostableHodlContract;
      require(name: "Dubi"): TruffleContracts.DubiContract;
      require(name: "DummyBoostable"): TruffleContracts.DummyBoostableContract;
      require(name: "DummyERC20"): TruffleContracts.DummyERC20Contract;
      require(
        name: "EIP712Boostable"
      ): TruffleContracts.EIP712BoostableContract;
      require(name: "ERC20"): TruffleContracts.ERC20Contract;
      require(name: "Hodl"): TruffleContracts.HodlContract;
      require(
        name: "IBoostableERC20"
      ): TruffleContracts.IBoostableERC20Contract;
      require(
        name: "IERC1820Registry"
      ): TruffleContracts.IERC1820RegistryContract;
      require(name: "IERC20"): TruffleContracts.IERC20Contract;
      require(name: "IHodl"): TruffleContracts.IHodlContract;
      require(name: "IOptIn"): TruffleContracts.IOptInContract;
      require(name: "Migrations"): TruffleContracts.MigrationsContract;
      require(name: "MintMath"): TruffleContracts.MintMathContract;
      require(name: "OptIn"): TruffleContracts.OptInContract;
      require(name: "Ownable"): TruffleContracts.OwnableContract;
      require(
        name: "ProtectedBoostable"
      ): TruffleContracts.ProtectedBoostableContract;
      require(
        name: "ProtectedBoostableLib"
      ): TruffleContracts.ProtectedBoostableLibContract;
      require(name: "Purpose"): TruffleContracts.PurposeContract;
    }
  }
}
